artifacts_root: artifacts

data_ingestion:
  root_dir: 'artifact/data_ingestion'
  raw_data_path: 'artifact/data_ingestion/raw.csv'
  train_data_path: 'artifact/data_ingestion/train.csv'
  test_data_path: 'artifact/data_ingestion/test.csv'

data_transformation:
  preprocessed_obj_file_path: 'artifact/data_transformation/preprocessed.pkl'
  scaled_train_path: 'artifact/data_transformation/scaled_train.csv'
  scaled_test_path: 'artifact/data_transformation/scaled_test.csv'
