artifacts_root: artifacts

data_ingestion:
  root_dir: 'artifact/data_ingestion'
  raw_data_path: 'artifact/data_ingestion/raw.csv'
  train_data_path: 'artifact/data_ingestion/train.csv'
  test_data_path: 'artifact/data_ingestion/test.csv'